/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlbumViewComponent {
        "albumtitle": string;
        "description": string;
        "energy": number;
        "gaveEnergy": boolean;
        "idx": string;
        "num": number;
        "position": number;
        "top": number;
    }
}
export interface AlbumViewComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAlbumViewComponentElement;
}
declare global {
    interface HTMLAlbumViewComponentElement extends Components.AlbumViewComponent, HTMLStencilElement {
    }
    var HTMLAlbumViewComponentElement: {
        prototype: HTMLAlbumViewComponentElement;
        new (): HTMLAlbumViewComponentElement;
    };
    interface HTMLElementTagNameMap {
        "album-view-component": HTMLAlbumViewComponentElement;
    }
}
declare namespace LocalJSX {
    interface AlbumViewComponent {
        "albumtitle"?: string;
        "description"?: string;
        "energy"?: number;
        "gaveEnergy"?: boolean;
        "idx"?: string;
        "num"?: number;
        "onEnergyUpdated"?: (event: AlbumViewComponentCustomEvent<any>) => void;
        "position"?: number;
        "top"?: number;
    }
    interface IntrinsicElements {
        "album-view-component": AlbumViewComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "album-view-component": LocalJSX.AlbumViewComponent & JSXBase.HTMLAttributes<HTMLAlbumViewComponentElement>;
        }
    }
}
